name: ml-pruning
channels:
  - conda-forge
  - pytorch 
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - hydra-core
  - wandb
  - timm
  - scipy
  - pandas