defaults:
  - dataset: ???
  - model: ???
  - optimizer: adamw

pruning:
  iteration_rate: ???
  iterations: ???
  finetune_epochs: ???
  early_stopping: False

wandb:
  logging: False
  project: pruning

seed:
  is_set: False
  value: ???

repeat: 1
save_checkpoints: False

dataloaders:
  pin_memory: True
  num_workers: 4
  batch_size: 128

early_stopper:
  patience: 20
  min_delta: 0.001
