defaults:
  - dataset: ???
  - model: ???
  - optimizer: adamw

pruning:
  iteration_rate: ???
  iterations: ???
  finetune_epochs: ???
  batch_size: 64

wandb:
  logging: False
  project: pruning

seed:
  torch: 42
  numpy: 42
  random: 42
